//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCSSStyles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCSSStyles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniEBoard.Resource.ResourceCSSStyles", typeof(ResourceCSSStyles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed.
        /// </summary>
        internal static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideControl.
        /// </summary>
        internal static string HideCSSClass {
            get {
                return ResourceManager.GetString("HideCSSClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radius.
        /// </summary>
        internal static string HighPriorityLablelCss {
            get {
                return ResourceManager.GetString("HighPriorityLablelCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radius plus10.
        /// </summary>
        internal static string LowPriorityLabelCss {
            get {
                return ResourceManager.GetString("LowPriorityLabelCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radius plus5.
        /// </summary>
        internal static string MediumPriorityLablelCss {
            get {
                return ResourceManager.GetString("MediumPriorityLablelCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        internal static string NoPriorityLablelCss {
            get {
                return ResourceManager.GetString("NoPriorityLablelCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label success radius.
        /// </summary>
        internal static string StatusQuestionAnswered {
            get {
                return ResourceManager.GetString("StatusQuestionAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label radius.
        /// </summary>
        internal static string StatusQuestionClosed {
            get {
                return ResourceManager.GetString("StatusQuestionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label radius.
        /// </summary>
        internal static string StatusQuestionNew {
            get {
                return ResourceManager.GetString("StatusQuestionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label success radius.
        /// </summary>
        internal static string StatusQuestionUpdated {
            get {
                return ResourceManager.GetString("StatusQuestionUpdated", resourceCulture);
            }
        }
    }
}
