//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.AnswerQuestionChoices = new HashSet<AnswerQuestionChoice>();
        }
    
        public int Id { get; set; }
        public int Question_Id { get; set; }
        public int QuizEntryId { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuizEntry QuizEntry { get; set; }
        public virtual ICollection<AnswerQuestionChoice> AnswerQuestionChoices { get; set; }
    }
}
