//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.Tags = new HashSet<Tag>();
            this.Units1 = new HashSet<Unit>();
            this.Assignments = new HashSet<Assignment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AssetType { get; set; }
        public string Path { get; set; }
        public int CompanyId { get; set; }
        public string ContentType { get; set; }
        public System.Guid IdentityToken { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Company Company { get; set; }
        public virtual Assets_WebPage Assets_WebPage { get; set; }
        public virtual ICollection<Unit> Units1 { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
    }
}
