//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.Submissions = new HashSet<Submission>();
            this.FileUploads = new HashSet<BaseFile>();
            this.Assets = new HashSet<Asset>();
        }
    
        public int Id { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime PublishFrom { get; set; }
        public System.DateTime PublishTo { get; set; }
        public Nullable<int> QuizId { get; set; }
        public string Title { get; set; }
        public string Instructions { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> PointsPossible { get; set; }
    
        public virtual ICollection<Submission> Submissions { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual Course Course { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<BaseFile> FileUploads { get; set; }
        public virtual Module Module { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
