//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseQuestionTopic
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public bool IsTopic { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public string Description { get; set; }
        public int OriginatorId { get; set; }
    
        public virtual User Originator { get; set; }
    }
}
