//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public Nullable<int> SubmissionId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public string Extension { get; set; }
        public string DateCreated { get; set; }
        public string FilePath { get; set; }
        public System.Guid IdentityToken { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual Submission Submission { get; set; }
        public virtual Assignment Assignment { get; set; }
    }
}
