//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Contacts = new HashSet<Contact>();
            this.Users = new HashSet<User>();
            this.Courses = new HashSet<Course>();
            this.Assets = new HashSet<Asset>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
