//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseModules = new HashSet<CourseModule>();
            this.CourseRegistrations = new HashSet<CourseRegistration>();
            this.StaffCourses = new HashSet<StaffCourse>();
            this.Assignments = new HashSet<Assignment>();
            this.Schedules = new HashSet<Schedule>();
            this.Discussions = new HashSet<Discussion>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }
        public string Length { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Approved { get; set; }
        public int Accreditation_Id { get; set; }
        public int CourseTemplate_Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int CompanyId { get; set; }
        public string Code { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual Accreditation Accreditation { get; set; }
        public virtual ICollection<CourseModule> CourseModules { get; set; }
        public virtual ICollection<CourseRegistration> CourseRegistrations { get; set; }
        public virtual ICollection<StaffCourse> StaffCourses { get; set; }
        public virtual CourseTemplate CourseTemplate { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Department Department { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Discussion> Discussions { get; set; }
    }
}
