//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseModule
    {
        public int Id { get; set; }
        public int Course_Id { get; set; }
        public int Module_Id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Module Module { get; set; }
    }
}
