//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document : Asset
    {
        public Document()
        {
            this.Units = new HashSet<Unit>();
        }
    
    
        public virtual ICollection<Unit> Units { get; set; }
    }
}
