//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.ViewedMessages = new HashSet<ViewedMessage>();
            this.GroupMessages = new HashSet<GroupMessage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int MessageType { get; set; }
        public int FromUserId { get; set; }
        public Nullable<int> RecipientUserId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> EntityId { get; set; }
        public bool MessageViewed { get; set; }
    
        public virtual User FromUser { get; set; }
        public virtual User RecipientUser { get; set; }
        public virtual ICollection<ViewedMessage> ViewedMessages { get; set; }
        public virtual ICollection<GroupMessage> GroupMessages { get; set; }
    }
}
