//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Assignments = new HashSet<Assignment>();
            this.CourseModules = new HashSet<CourseModule>();
            this.ModuleQuizs = new HashSet<ModuleQuiz>();
            this.Units = new HashSet<Unit>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Score { get; set; }
        public bool Approved { get; set; }
        public int CreatedByStaff_Id { get; set; }
        public int Course_Id { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<CourseModule> CourseModules { get; set; }
        public virtual ICollection<ModuleQuiz> ModuleQuizs { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual Staff Users_Staff { get; set; }
    }
}
