//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.QuestionChoices = new HashSet<QuestionChoice>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool AllowMultipleSelections { get; set; }
        public string HelpText { get; set; }
        public int Quiz_Id { get; set; }
        public int QuestionType_Id { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<QuestionChoice> QuestionChoices { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
