//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizEntry
    {
        public QuizEntry()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public int Student_Id { get; set; }
        public int Quiz_Id { get; set; }
        public Nullable<int> QuizResult { get; set; }
    
        public virtual Quiz Quiz { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
    }
}
