//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public int CourseId { get; set; }
        public int UnitId { get; set; }
        public Nullable<System.DateTime> ScheduledFrom { get; set; }
        public Nullable<System.DateTime> ScheduledTo { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
