//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff : User
    {
        public Staff()
        {
            this.StaffCourses = new HashSet<StaffCourse>();
            this.Units = new HashSet<Unit>();
            this.Groups_1 = new HashSet<Group>();
            this.Modules = new HashSet<Module>();
        }
    
        public int Position_Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<StaffCourse> StaffCourses { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<Group> Groups_1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
    }
}
