//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicPost
    {
        public TopicPost()
        {
            this.ReplyPosts = new HashSet<TopicPost>();
            this.Discussions = new HashSet<Discussion>();
        }
    
        public int Id { get; set; }
        public string IP { get; set; }
        public string Title { get; set; }
        public int Status { get; set; }
        public string Body { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Votes { get; set; }
        public int PostedByUserId { get; set; }
        public Nullable<int> ParentTopicPostId { get; set; }
        public int TopicId { get; set; }
    
        public virtual User PostedByUser { get; set; }
        public virtual ICollection<TopicPost> ReplyPosts { get; set; }
        public virtual TopicPost ParentPost { get; set; }
        public virtual Topic Topic { get; set; }
        public virtual ICollection<Discussion> Discussions { get; set; }
    }
}
