//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Schedules = new HashSet<Schedule>();
            this.Assets = new HashSet<Asset>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishFrom { get; set; }
        public Nullable<System.DateTime> PublishTo { get; set; }
        public int StaffId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> VideoId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> QuizId { get; set; }
        public Nullable<double> Duration { get; set; }
    
        public virtual Staff CreatedByStaff { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Video Video { get; set; }
        public virtual Document Document { get; set; }
        public virtual Module Module { get; set; }
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
