//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniEBoard.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tasks = new HashSet<Task>();
            this.Permissions = new HashSet<Permission>();
            this.Roles = new HashSet<Role>();
            this.CreatedMessages = new HashSet<Message>();
            this.ReceivedMessages = new HashSet<Message>();
            this.UserViewedMessages = new HashSet<ViewedMessage>();
            this.UserGroups = new HashSet<UserGroup>();
            this.PostedTopicPosts = new HashSet<TopicPost>();
            this.CreatedBaseQuestionTopics = new HashSet<BaseQuestionTopic>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int UserGender { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public bool AccountDisabled { get; set; }
        public int Membership_Id { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Message> CreatedMessages { get; set; }
        public virtual ICollection<Message> ReceivedMessages { get; set; }
        public virtual ICollection<ViewedMessage> UserViewedMessages { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        public virtual ICollection<TopicPost> PostedTopicPosts { get; set; }
        public virtual ICollection<BaseQuestionTopic> CreatedBaseQuestionTopics { get; set; }
        public virtual Company Company { get; set; }
    }
}
